name: Build and run tests

on:
    push:
    pull_request:

jobs:
    build_php8:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP 8.0
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.0'

            - name: Validate composer.json and composer.lock
              run: composer validate

            - name: Install dependencies
              if: steps.composer-cache.outputs.cache-hit != 'true'
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: Run test suite
              run: composer run-script test
    build_php81:

      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Setup PHP 8.1
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.1'

        - name: Validate composer.json and composer.lock
          run: composer validate

        - name: Install dependencies
          if: steps.composer-cache.outputs.cache-hit != 'true'
          run: composer install --prefer-dist --no-progress --no-suggest

        - name: Run test suite
          run: composer run-script test
    build_php82:

      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Setup PHP 8.2
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.2'

        - name: Validate composer.json and composer.lock
          run: composer validate

        - name: Install dependencies
          if: steps.composer-cache.outputs.cache-hit != 'true'
          run: composer install --prefer-dist --no-progress --no-suggest

        - name: Run test suite
          run: composer run-script test
    build_php83:

      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: Setup PHP 8.3
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.3'

        - name: Validate composer.json and composer.lock
          run: composer validate

        - name: Install dependencies
          if: steps.composer-cache.outputs.cache-hit != 'true'
          run: composer install --prefer-dist --no-progress --no-suggest

        - name: Run test suite
          run: composer run-script test